In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\Hp\Desktop\ML_ASSIGNMENT\5000songs.csv")

In [4]:
df.head()

user_id     song_id   valence  danceability      tempo    energy  \
0  user_071  song_00001  0.580307      0.884519  86.346072  0.930996   
1  user_013  song_00001  0.580307      0.884519  86.346072  0.930996   
2  user_060  song_00001  0.580307      0.884519  86.346072  0.930996   
3  user_035  song_00001  0.580307      0.884519  86.346072  0.930996   
4  user_067  song_00001  0.580307      0.884519  86.346072  0.930996   

   acousticness  instrumentalness  liveness  speechiness  ...  artist_id  \
0      0.767026           0.63069   0.54445     0.871949  ...  artist_23   
1      0.767026           0.63069   0.54445     0.871949  ...  artist_23   
2      0.767026           0.63069   0.54445     0.871949  ...  artist_23   
3      0.767026           0.63069   0.54445     0.871949  ...  artist_23   
4      0.767026           0.63069   0.54445     0.871949  ...  artist_23   

   album_id  artist_familiarity  past_listens  user_genre_affinity  \
0  album_45            0.834276             2             0.291001   
1  album_45            0.421589             5             0.409874   
2  album_45            0.808128             4             0.303511   
3  album_45            0.390714             9             0.007649   
4  album_45            0.139208             1             0.193991   

  user_artist_affinity day_of_week time_of_day  context_type  \
0             0.081154    Thursday       Night      playlist   
1             0.010343      Friday   Afternoon         radio   
2             0.066675    Thursday     Evening         album   
3             0.122987      Sunday   Afternoon      playlist   
4             0.082900      Friday       Night         radio   

   listened_repeatedly  
0                    0  
1                    1  
2                    1  
3                    1  
4                    0  

[5 rows x 26 columns]

In [5]:
df.listened_repeatedly.unique()

array([0, 1], dtype=int64)

In [6]:
y = df['listened_repeatedly']

In [7]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: listened_repeatedly, dtype: int64

In [8]:
X = df.drop('listened_repeatedly', axis=1)
X.head()

user_id     song_id   valence  danceability      tempo    energy  \
0  user_071  song_00001  0.580307      0.884519  86.346072  0.930996   
1  user_013  song_00001  0.580307      0.884519  86.346072  0.930996   
2  user_060  song_00001  0.580307      0.884519  86.346072  0.930996   
3  user_035  song_00001  0.580307      0.884519  86.346072  0.930996   
4  user_067  song_00001  0.580307      0.884519  86.346072  0.930996   

   acousticness  instrumentalness  liveness  speechiness  ...  genre  \
0      0.767026           0.63069   0.54445     0.871949  ...    Pop   
1      0.767026           0.63069   0.54445     0.871949  ...    Pop   
2      0.767026           0.63069   0.54445     0.871949  ...    Pop   
3      0.767026           0.63069   0.54445     0.871949  ...    Pop   
4      0.767026           0.63069   0.54445     0.871949  ...    Pop   

   artist_id  album_id  artist_familiarity  past_listens user_genre_affinity  \
0  artist_23  album_45            0.834276             2            0.291001   
1  artist_23  album_45            0.421589             5            0.409874   
2  artist_23  album_45            0.808128             4            0.303511   
3  artist_23  album_45            0.390714             9            0.007649   
4  artist_23  album_45            0.139208             1            0.193991   

  user_artist_affinity day_of_week  time_of_day  context_type  
0             0.081154    Thursday        Night      playlist  
1             0.010343      Friday    Afternoon         radio  
2             0.066675    Thursday      Evening         album  
3             0.122987      Sunday    Afternoon      playlist  
4             0.082900      Friday        Night         radio  

[5 rows x 25 columns]

In [9]:
y.shape

(25067,)

In [11]:
X.shape

(25067, 25)

In [12]:
# split the data into train & test set
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [14]:
X_train.shape

(20053, 25)

In [15]:
X_test.shape

(5014, 25)

In [16]:
y_train.shape

(20053,)

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
clr = RandomForestClassifier()

In [19]:
clr.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [23]:
print(X_train)

        user_id     song_id   valence  danceability       tempo    energy  \
55     user_075  song_00011  0.484575      0.219864   65.893451  0.582685   
1830   user_002  song_00369  0.711138      0.291172   72.303385  0.440671   
202    user_032  song_00040  0.109544      0.336118  129.552002  0.195057   
8789   user_041  song_01754  0.625666      0.126230  105.047078  0.123221   
9805   user_069  song_01957  0.385658      0.282505  158.039017  0.196911   
...         ...         ...       ...           ...         ...       ...   
19690  user_087  song_03925  0.731788      0.819833   84.658739  0.647496   
25064  user_051  song_05000  0.672708      0.755864   75.161836  0.285078   
19616  user_027  song_03911  0.131376      0.162965  142.870480  0.275369   
4999   user_003  song_00998  0.066926      0.955812  176.872391  0.016197   
1842   user_023  song_00371  0.259041      0.826229   77.351542  0.024169   

       acousticness  instrumentalness  liveness  speechiness  ...      genr

In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier  # Or any other classifier

# Assuming you have your data loaded into a DataFrame called 'df'
# and your target variable is 'target'

# Separate features (X) and target (y)
X = df.drop('user_id', axis=1)
y = df['user_id']



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Assuming your DataFrame is called 'df'

# Separate features (X) and target (y)
X = df.drop('genre', axis=1)
y = df['genre']

# Identify categorical and numerical columns
categorical_cols = ['user_id', 'song_id', 'artist_id', 'album_id', 'day_of_week', 'time_of_day', 'context_type']
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Create a preprocessor using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ])

# Encode the target variable 'genre'
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Create a pipeline with preprocessing and a classifier
model = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', RandomForestClassifier(random_state=42))])

# Fit the model
model.fit(X_train, y_train)



Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['valence', 'danceability',
                                                   'tempo', 'energy',
                                                   'acousticness',
                                                   'instrumentalness',
                                                   'liveness', 'speechiness',
                                                   'loudness', 'mode', 'key',
                                                   'duration_ms',
                                                   'cluster_label',
                                                   'artist_familiarity',
                                                   'past_listens',
                                                   'user_genre_affinity',
                                                   'user_artist_affinity',
                                                   'listened_repeatedly']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['user_id', 'song_id',
                                                   'artist_id', 'album_id',
                                                   'day_of_week', 'time_of_day',
                                                   'context_type'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [30]:
y_pred = model.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score; accuracy_score(y_test, y_pred)

0.9924212205823694

In [32]:
from sklearn.metrics import classification_report; print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       449
           1       0.98      1.00      0.99       495
           2       1.00      0.99      1.00       509
           3       1.00      0.99      0.99       500
           4       0.99      1.00      0.99       483
           5       1.00      0.99      1.00       526
           6       0.98      0.99      0.99       495
           7       1.00      1.00      1.00       505
           8       0.99      0.99      0.99       499
           9       0.99      0.98      0.99       553

    accuracy                           0.99      5014
   macro avg       0.99      0.99      0.99      5014
weighted avg       0.99      0.99      0.99      5014



In [33]:
from sklearn.metrics import confusion_matrix; print(confusion_matrix(y_test, y_pred))

[[441   0   0   0   0   0   4   1   3   0]
 [  0 493   1   0   0   0   1   0   0   0]
 [  2   1 506   0   0   0   0   0   0   0]
 [  1   1   0 495   0   0   0   1   0   2]
 [  0   0   0   0 482   0   0   0   0   1]
 [  0   0   0   1   2 522   1   0   0   0]
 [  0   2   0   0   1   0 492   0   0   0]
 [  0   0   0   0   0   0   0 505   0   0]
 [  0   3   0   0   0   0   0   0 496   0]
 [  3   1   0   0   2   0   3   0   0 544]]


In [35]:
#to see the predictions in their original string format 
original_genre_predictions = label_encoder.inverse_transform(y_pred)

In [ ]:
model.predict(X_test)

array([8, 8, 7, ..., 8, 5, 9])